server:
  port: 9005

spring:
  application:
    name: xdclass-product-service
  profiles:
    active: prd

  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.179.20/pass_product?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: a123jiayoua

  #nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 47.98.179.20:8848
#redis 配置
  redis:
    host: 47.98.179.20
    port: 8000
    password: 123456

# dubbo
#dubbo:
#  application:
#    name: consumer-server
#    qos-accept-foreign-ip: false
#    qos-enable: false
#  scan:
#    base-packages: com.simh.service
#  protocol:
#    name: dubbo
#    port: -1
#  registry:
#    address: nacos://127.0.0.1:8848
#    protocol: nacos

#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO


