server:
  port: 9006

spring:
  application:
    name: xdclass-order-service
  profiles:
    active: prd
  #nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 47.98.179.20:8848

  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.179.20/pass_product?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: a123jiayoua

  #redis 配置
  redis:
    host: 47.98.179.20
    port: 8000
    password: 123456

#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO
