server:
  port: 9003

spring:
  application:
    name: xdclass-user-service

#数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.179.20/pass_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
#redis 配置
  redis:
    host: 47.98.179.20
    port: 8000
    password: 123456
#邮箱配置
  mail:
    host: smtp.163.com #发邮件服务器
    username: ssmh0201@163.com  #发送邮件的邮箱地址
    password: FJSBWPUVDUZXCFZV  #客户端授权码
    from: ssmh0201@163.com #发送邮件的邮箱地址
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO
